### ISSUE TITLE
Add labels like in the gistbox app

### ISSUE THREAD

**Issue by Grapefish** [Gisto/Gisto#155]
In Gistbox users can create labels to organise gists.
It would be nice to have this feature in Gisto.

**Comment by morsdyce** [comment]
Hi @Grapefish 

You can add tags to gists in order to find them quickly, simple include a #tag in the description of the gist and we will be able to filter these out based on search.

See Tag Gist section in http://www.gistoapp.com/documentation/

Thanks

**Comment by Grapefish** [comment]
I know that's possible, but I think it would be a handy feature.
So you can organise your gists in multiple ways.

**Comment by morsdyce** [comment]
Do you mean having a clickable label on the side to view these gists?

**Comment by Grapefish** [comment]
Yes that's exactly what I meant.

**Comment by morsdyce** [comment]
Due to our current layout its not possible to do something like that.

However we had an idea about integrating it into a keyboard shortcut that will display a modal window with all the tags. The tags can be clicked or accessed via a keyboard shortcut attached to them.

We would love feedback if you think this is a good fit to this solution or if you have any other suggestions.

**Comment by sanusart** [comment]
ref v2: 00f7ae9be2ecc2183fe79dc56054df62aa97e548

**Comment by sanusart** [comment]
Closing: exists starts from v1.9.61 (tags and grouped files on the dashboard)
