### ISSUE TITLE
Show a more meaningful message when a Gist file name contains an illegal character 

### ISSUE THREAD

**Issue by clivethescott** [Gisto/Gisto#176]
When adding a file with a forward slash character in the name it shows multiple messages saying "You cannot save empty files"

**Comment by morsdyce** [comment]
This is something that we are currently working on, handling more types of error responses from github and showing a more appropriate message and improve the validation of files before sending.

Will update once we have something working.

Thanks for the feedback!

**Comment by morsdyce** [comment]
Just to update, I contacted GitHub support on where I can get a list of validation errors for the gist api.

To my surprise I received a response that those errors are not public, which is utterly stupid because we need to guess what errors can be, or try to break the api with multiple requests and figure out what passes validation or not.

The API validation messages are most of the time not helpful and are not formatted for end users.

If anyone knows what are the things you are not allowed to do in gists please list them here.
