### ISSUE TITLE
question about comments..

### ISSUE THREAD

**Issue by magnusprime27** [Gisto/Gisto#209]
if I post a comment on my gist in gisto, it appears in the comments of the gist on github..BUT, doesn't show comments commented on the gist on github on gisto..
hope that made sence. is this an issue or do I not have something set right?

**Comment by sanusart** [comment]
Hey @magnusprime27 
Do you mean you don't ever see it? Or you don't see it immediately? Because there is some delay until it is going to appear. What you can do it try to force sync by pressing 
![image](https://user-images.githubusercontent.com/267718/35474150-ea3723fe-0392-11e8-810f-3b707843b46f.png) 
on top pannel. This will force all but active Gist to update.
