### ISSUE TITLE
Local DB Support

### ISSUE THREAD

**Issue by darkworks** [Gisto/Gisto#211]
it will be good of gisto maintain local db in case github account is lost or something worst happen , so it will be good if gisto keep copy of snippets in local database on system which could be accessible from guest account anytime

**Comment by sanusart** [comment]
We plan to implement local db to some extent in order to support offline
editing, it might be used to keep track of snippets locally, but I am not
sure gisto should be considered as a backup solution of any sort.

I am gonna close it for now as it is not a direction gisto currently want
to take in my opinion. We might consider some export solution at some point
though. Hard to say.

**Comment by sanusart** [comment]
Been thinking about it more. I don't think Gisto should/can be seen as a gists backup solution. 
So I'll really close it for now.
