### ISSUE TITLE
is there a way to use 'latest-mac.yml' to check for latest Mac version?

### ISSUE THREAD

**Issue by tjluoma** [Gisto/Gisto#281]
I am trying to find a reliable way of identifying the latest Mac version.

The download page at https://www.gistoapp.com/#download does not seem to actually link to a Mac version, and I don't want to use `brew cask`.

I see that some releases have a 'latest-mac.yml' file. I am wondering if there is a permalink to that file somewhere that might always point to the latest Mac release.

Failing that, any other suggestions would be welcome.

**Comment by sanusart** [comment]
It is not in the download page right now because new version is currently deploying :)
After it is deployed it will be ther, but you always get notification about new versions on MacOS and windows with a little yellow bolt icon on the toolbar.
![image](https://user-images.githubusercontent.com/267718/77216197-4c837d80-6b21-11ea-9a77-c9a1348e51c8.png)
After you click it you can see that new version is available and choose to download.
![image](https://user-images.githubusercontent.com/267718/77216215-789efe80-6b21-11ea-9513-40a80dc52f87.png)

**Comment by sanusart** [comment]
Try to open the app now and you'll see it as it is just deployed I think. Also links at the website are active.

**Comment by tjluoma** [comment]
Ah! Ok, poor timing, I guess.
